# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoSearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoSearch

  target 'PhotoSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoSearchUITests' do
    # Pods for testing
  end
  pod 'SnapKit', '~> 5.6.0'
end
